### PR TITLE
Fix for issue #11: wrong origins in collision mesh

### PR DESCRIPTION
**Pull request by gavanderhoorn**
This was (apparently) not completely fixed in b2326cbd.

Also a minor change to the origin of the `visual` mesh of `link_6`, but that is mostly cosmetic.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@shaun-edwards: if I could bother you with this?

**Comment by gavanderhoorn** [comment]
@muhrix: make sure you have this change merged in your local clone until this has been merged. Without it I don't think MoveIt's collision detection/avoidance will correctly work for your RX160L.

**Comment by muhrix** [comment]
Thanks for the tip!

**Comment by gavanderhoorn** [comment]
Friendly ping?

**Comment by shaun-edwards** [comment]
+1

**Comment by gavanderhoorn** [comment]
Thanks.

**Pull request merged**
