### PR TITLE
Fix for issue #9: make all files use spaces for indentation

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

No functional changes.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@shaun-edwards: could you take a look?

**Comment by gavanderhoorn** [comment]
Friendly ping

**Comment by shaun-edwards** [comment]
Verified only white space changes (neat [trick](https://github.com/ros-industrial/staubli/pull/14/files?w=1)).  +1

**Comment by gavanderhoorn** [comment]
:). Nice trick indeed :).

**Pull request merged**
