### PR TITLE
Fix for issue #21: add missing run_depend to rx160_support

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@shaun-edwards: could I bother you to take a look?

**Comment by gavanderhoorn** [comment]
Ping? :)

**Comment by gavanderhoorn** [comment]
@MuriloMartins: if you have a minute?

**Comment by shaun-edwards** [comment]
+1  Sorry for delay.  Thanks for the contribution.

**Comment by gavanderhoorn** [comment]
Thanks @shaun-edwards.

No problem.

**Pull request merged**
