### PR TITLE
add melodic and melodic-testing

### PR DESCRIPTION
**Pull request by simonschmeisser**
this adds melodic as a test target (due to api changes) and also changes indigo/ros-shadow-fixed to melodic/ros-testing. However I have to admit I don't know the full rationale behind listing testing/shadow-fixed here as changes there/in dependencies won't trigger a rebuild?

### CODE REVIEW

**Comment by simonschmeisser** [comment]
note that this is expected to fail till #30 is merged

**Review by gavanderhoorn — CHANGES_REQUESTED** [review]
Thanks for the PR.

Some comments:

> this adds melodic as a test target (due to api changes) 

Great. Thanks.

> and also changes indigo/ros-shadow-fixed to melodic/ros-testing. 

Could you please either revert this or do this in a second commit?

For now just adding two new rows for Melodic would be preferred.

**Comment by simonschmeisser** [comment]
rebased and done

**Comment by gavanderhoorn** [comment]
@simonschmeisser: could you rebase again? This should now pass.

**Comment by simonschmeisser** [comment]
> @simonschmeisser: could you rebase again? This should now pass.

it does :)

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Thanks @simonschmeisser :+1: 

:beers:

**Comment by simonschmeisser** [comment]
Glad to contribute :)

**Pull request merged**
