### PR TITLE
Add some more default colours to resources package

### PR DESCRIPTION
**Pull request by gavanderhoorn**
New colours based on information I received from Staubli directly.

Comments in `common_colours.xacro` provide hints as to for which types/models/variants specific colours should be used.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@MuriloMartins: do you think you could take a look?

I've moved Zinc Yellow (RAL1018) and Traffic Grey B (RAL7043) to the deprecated section, as they aren't standard colours. The RX160(L) macros still use those, so we'll have to change that, but for now it's ok.

**Comment by MuriloMartins** [comment]
From the deprecated list the last 2 colours were added in ros-industrial/staubli#15, so I reckon we could just get rid of that since I'm probably the only one using that at the moment...

**Comment by gavanderhoorn** [comment]
I'll remove the two 'new' deprecated colours in a separate PR, so as to not mix things up. That PR will also update the RX160 macros.

**Comment by MuriloMartins** [comment]
Great!

**Pull request merged**
