### PR TITLE
resources: remove non-standard RAL colours and material defs

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

@MuriloMartins: agree?

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Unfortunately this does mean that `link_6` will be 'Melon Yellow' as well, which is not so nice.

**Comment by MuriloMartins** [comment]
I actually just came back from the lab and I noticed that links 5 and 6 are grey/aluminium.
How about using RAL 9007 (`colour_staubli_ral_grey_aluminium`) for those links?

**Comment by gavanderhoorn** [comment]
Also good.

All these colours are approximations anyway. If you'd really want more realism, we'd have to move to using Collada meshes for all links.

**Comment by gavanderhoorn** [comment]
Done.

**Comment by MuriloMartins** [comment]
Realistic textures with Collada would be a nice improvement, but I think solid colours are just fine.
The .stl meshes are nice because GitHub can render them.

**Comment by MuriloMartins** [comment]
@gavanderhoorn +1

**Comment by gavanderhoorn** [comment]
Thanks.

**Pull request merged**
